// Async
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_LOADING = 'GET_POSTS_LOADING';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';
export const GET_POSTS_BY_USER_ID = 'GET_POSTS_BY_USER_ID';
export const GET_POSTS_BY_USER_ID_LOADING = 'GET_POSTS_BY_USER_ID_LOADING';
export const GET_POSTS_BY_USER_ID_SUCCESS = 'GET_POSTS_BY_USER_ID_SUCCESS';
export const GET_POSTS_BY_USER_ID_ERROR = 'GET_POSTS_BY_USER_ID_ERROR';
